### ISSUE TITLE
URL bar doesn't hide since v133

### ISSUE THREAD

**Issue by rockofox** [rockofox/firefox-minima#15]
<img width="2524" alt="grafik" src="https://github.com/user-attachments/assets/3edfa154-8012-4358-a9d5-5841e28e7b35">

Also, the toolbar doesn't seem to fully reappear after focussing the URL bar

**Comment by yuandi42** [comment]
Though URL bar is (maybe) properly hidden, I still suffer from some strange behaviors around the bar.
1. when URL bar is launched, the main rendering content below would be pushed little downward. It caused frustrating flicking, especially when the website is height-dependent. (e.g., YouTube.)
2. again, when URL bar is launched, the tab bar would be slightly enlarge. Here is picture. I use Alpenglow theme so that the effect can be more obvious: 
   ![p2](https://github.com/user-attachments/assets/1714fd9a-7770-4dbd-b5cc-225a604ff590)
3. when typing in URL bar, the 🔍 icon would move slightly righted with the popup recommend URLs list.
   [p3.webm](https://github.com/user-attachments/assets/7213f55c-2e99-40f0-88d1-895c6732b4ee)

Those are not serious bugs, but once you noticed them, them would become more and more annoying...

**Comment by Xorger23** [comment]
I've also noticed that the tab bar seems slightly thicker now in general, not just when showing the URL bar.

**Comment by Xorger23** [comment]
It also seems to still be cut off, I'm running the latest version.
